### PR TITLE
Add qemu-shutdown script

### PR DESCRIPTION
**Pull request by tfussell**
Copied from https://github.com/giantswarm/k8s-kvm/pull/94

This script is called as a preStop hook here https://github.com/giantswarm/kvm-operator/blob/v3.17.3/service/controller/resource/deployment/master_deployment.go#L282

### CODE REVIEW

**Comment by tfussell** [comment]
@giantswarm/team-rocket Do you think this should be a shell script as it is in `k8s-kvm` or should I translate it into go code to make it nicer?

**Comment by tfussell** [comment]
Also we don't currently have networking in the `containervmm` container so I'm not sure if this is even the right approach (i.e. network requests will fail).

**Comment by mazzy89** [comment]
I definitely vote to nuke this old script and move the logic inside closer to the QMP socket. Further in fact as you said there is no network in the container itself so we need to orchestrate this mechanism from the QMP interface.

**Comment by tfussell** [comment]
As far as I understand, the QMP socket only gives us information about the virtual machine while the shutdown deferrer checks the Kubernetes API for information about the corresponding WC node so I don't see a way to avoid networking. I have tried to translate the shell script into Go code at least. Let me know what you think @giantswarm/team-rocket.

**Pull request closed without merging**
